# Generated by Django 5.0 on 2023-12-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/none/noimg.png', upload_to='images/'),
        ),
    ]
